In [8]:
!pip install scikit-learn

     |████████████████████████████████| 24.9 MB 34 kB/s  eta 0:00:01   |▏                               | 102 kB 558 kB/s eta 0:00:45     |██████████████▊                 | 11.4 MB 3.2 MB/s eta 0:00:05     |███████████████████████▌        | 18.3 MB 4.3 MB/s eta 0:00:02
     |████████████████████████████████| 303 kB 2.9 MB/s eta 0:00:01
     |████████████████████████████████| 27.2 MB 2.8 kB/s eta 0:00:01


In [9]:
import numpy as np
import random
from sklearn.metrics import mean_squared_error

# Inicializando matriz de movimientos validos
>Creamos las posibilidades en un array de 4,16,16 siendo 4 los movimientos(izquierda, derecha, arriba y abajo) y las otras dos dimensiones de la matriz para cada acción


In [10]:
Prob = np.array([[[1, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [1, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 1, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 1, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],    #izauierda
                   [0, 0, 0, 0, 0, 1, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 1, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 1,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 1,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  1,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  1,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  1,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  1,  0]],

                  [[0, 1, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 1, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 1, 0,  0,  0,  0,  0,  0,  0,  0],   # derecha
                   [0, 0, 0, 0, 0, 0, 0, 1, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  1,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  1,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  1,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  1],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  1]],

                  [[1, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 1, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 1, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 1, 0, 0,  0,  0,  0,  0,  0,  0,  0], # arriba
                   [0, 0, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 1, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 1, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 1, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 1,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  1,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  1,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  1]],

                  [[1, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 1, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 1, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0], # Abajo
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  1,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  1,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  1,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  1,  0,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  1,  0,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  1,  0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  1]]], dtype=float)

In [11]:
red_square = 4
green_square = 11
neig_red = [(5,0),(8,2)]
neig_gree = [(7,3),(10,1)]
states = Prob.shape[1] #16
actions = Prob.shape[0] #4
print("states:",states)
print("actions:", actions)


states: 16
actions: 4


In [12]:
#ejercicio a
rewards_ = [{"rs":-1.0},{"rs":0.0},{"rs":1.0}]
policies = []
gamma = 1.0

In [17]:
def value_actions(num_states, num_actions, state, rewards, gamma, Mat_pro, Vec_val):
    max_val = None
    max_action = None
    for action in range(num_actions):
        suma = 0
        for state_in in range(num_states):
            suma += Mat_pro[action,state,rewards] * Vec_val[state_in]
        value = rewards[state,action]+gamma*suma
        if max_val == None or max_val < value:
            max_val = value
            max_action = action
    return max_val, max_action
            
        

In [19]:
for rew in rewards_:
    V_old = np.zeros(states,dtype=float)
    V_new = np.zeros(states,dtype=float)
    rewards = np.full((states,actions),rew["rs"],dtype=float)
    print("rr",rewards)
    for state_action in neig_red:
        rewards[state_action[0],state_action[1]] = -5.0
    for state_action in neig_gree:
        rewards[state_action[0],state_action[1]] = 5.0
    for action in range(actions):
        rewards[red_square,action] = 0.0
    for action in range(actions):
        rewards[green_square,action] = 0.0
    policy = np.zeros(states,dtype=int)
    iterations = 0
    while True:
        for state in range(states):
            val, action = value_actions(states,actions,state,rewards,gamma,Prob,V_old)
            v_new[state] = val
            policy[state] = action
            if mean_square_error(V_old,V_new) < 0.001:
                break
            V_old = np.copy(V_new)
            iterations+=1
            if iterations >= 1000:
                print("No converge")
                break
    policies.append(policy)
    print("iteraciones:",iterations)
    print("politica",polyci)
    print("Valor",V_new)


rr [[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


IndexError: arrays used as indices must be of integer (or boolean) type